const demoAssignments = [
  {activity:'Piling - Drilling', code:'CIV1-0005', owner:'Arun Kumar', initials:'AK', milestone:'Civil-10', due:'06 Sep 2026', progress:100, status:'Completed'},
  {activity:'Piling Concreting', code:'CIV1-0012', owner:'Meena Shah', initials:'MS', milestone:'Civil-11', due:'08 Sep 2026', progress:60, status:'In progress'},
  {activity:'Civil works for Tigadi Deepak site', code:'CIV1-0028', owner:'Deepak Rao', initials:'DR', milestone:'Civil-12', due:'05 Sep 2026', progress:40, status:'Overdue'},
  {activity:'Civil works for LT room', code:'CIV1-0014', owner:'Priya Nair', initials:'PN', milestone:'Civil-13', due:'10 Sep 2026', progress:0, status:'Not started'},
  {activity:'Transformer foundation', code:'CIV1-0007', owner:'Arun Kumar', initials:'AK', milestone:'Civil-14', due:'11 Sep 2026', progress:100, status:'Completed'},
  {activity:'Equipment foundation', code:'CIV1-0008', owner:'Meena Shah', initials:'MS', milestone:'Civil-15', due:'12 Sep 2026', progress:80, status:'In progress'},
  {activity:'Street Lighting Foundation', code:'CIV1-0015', owner:'Deepak Rao', initials:'DR', milestone:'Civil-16', due:'03 Sep 2026', progress:25, status:'Overdue'},
  {activity:'Module mounting structure', code:'ELE1-0003', owner:'Priya Nair', initials:'PN', milestone:'Elec-04', due:'14 Sep 2026', progress:100, status:'Completed'},
  {activity:'DC cable trenching', code:'ELE1-0008', owner:'Arun Kumar', initials:'AK', milestone:'Elec-08', due:'15 Sep 2026', progress:100, status:'Completed'},
  {activity:'Inverter installation', code:'ELE1-0011', owner:'Meena Shah', initials:'MS', milestone:'Elec-11', due:'16 Sep 2026', progress:55, status:'In progress'},
  {activity:'AC cable laying', code:'ELE1-0016', owner:'Deepak Rao', initials:'DR', milestone:'Elec-16', due:'01 Sep 2026', progress:45, status:'Overdue'},
  {activity:'Earthing and lightning protection', code:'ELE1-0020', owner:'Priya Nair', initials:'PN', milestone:'Elec-20', due:'18 Sep 2026', progress:0, status:'Not started'},
  {activity:'SCADA communication setup', code:'ELE1-0024', owner:'Arun Kumar', initials:'AK', milestone:'Elec-24', due:'20 Sep 2026', progress:100, status:'Completed'},
  {activity:'Weather monitoring station', code:'ELE1-0028', owner:'Meena Shah', initials:'MS', milestone:'Elec-28', due:'22 Sep 2026', progress:100, status:'Completed'},
  {activity:'Testing and commissioning', code:'COM1-0002', owner:'Deepak Rao', initials:'DR', milestone:'Comm-02', due:'24 Sep 2026', progress:30, status:'In progress'},
  {activity:'Quality inspection dossier', code:'COM1-0005', owner:'Priya Nair', initials:'PN', milestone:'Comm-05', due:'25 Sep 2026', progress:100, status:'Completed'},
  {activity:'As-built documentation', code:'COM1-0007', owner:'Arun Kumar', initials:'AK', milestone:'Comm-07', due:'27 Sep 2026', progress:100, status:'Completed'},
  {activity:'Project handover pack', code:'COM1-0010', owner:'Meena Shah', initials:'MS', milestone:'Comm-10', due:'30 Sep 2026', progress:0, status:'Not started'}
];
let assignments = [...demoAssignments];
const $ = (id) => document.getElementById(id);
function setActiveReportName(name) { const reportName = $('active-report-name'); if (reportName) reportName.textContent = name || 'the selected report'; }
function formatNumber(value){const number=Number(value);return Number.isFinite(number)?number.toLocaleString('en-IN',{maximumFractionDigits:2}):'0';}
function reportValue(value){return value === '' || value === null || value === undefined ? 0 : value;}
function statusClass(status){ return status.toLowerCase().replaceAll(' ','-'); }
function renderMetrics(){ $('assigned-count').textContent=assignments.length; $('completed-count').textContent=assignments.filter(x=>x.status==='Completed').length; $('progress-count').textContent=assignments.filter(x=>x.status==='In progress').length; $('overdue-count').textContent=assignments.filter(x=>x.status==='Overdue').length; }
function renderPeople(){ const people={}; assignments.forEach(x=>{ if(!people[x.owner]) people[x.owner]={initials:x.initials,total:0,completed:0,progress:0}; people[x.owner].total++; if(x.status==='Completed')people[x.owner].completed++; people[x.owner].progress+=x.progress; }); const colors=['','alt','blue','alt']; $('people-list').innerHTML=Object.entries(people).map(([name,p],i)=>{const pct=Math.round(p.progress/p.total); return `<div class="person-row"><div class="person-avatar ${colors[i%colors.length]}">${p.initials}</div><div><div class="person-name">${name}</div><div class="person-meta">${p.completed} of ${p.total} completed</div></div><div><div class="bar-track"><div class="bar-fill ${i%3===1?'amber':i%3===2?'blue':''}" style="width:${pct}%"></div></div><div class="person-percent">${pct}% complete</div></div></div>`}).join(''); }
function renderActivity(){ const recent=assignments.slice(0,3).map((item,index)=>[item.activity,`${item.status} · ${item.project||'Project report'}`,index===0?'Latest row':'Imported report',item.status==='Overdue'?'orange':'']); $('activity-list').innerHTML=recent.map(x=>`<div class="activity-item"><span class="activity-line ${x[3]}"></span><div class="activity-text"><strong>${x[0]}</strong><br>${x[1]}</div><span class="activity-time">${x[2]}</span></div>`).join(''); }
function renderTable(){ const query=$('search-input').value.toLowerCase(); const filter=$('status-filter').value; const rows=assignments.filter(x=>(filter==='all'||x.status===filter)&&(!query||`${x.activity} ${x.owner} ${x.code}`.toLowerCase().includes(query))); $('table-count').textContent=rows.length; $('assignment-table').innerHTML=rows.map(x=>`<tr><td><div class="activity-title">${x.activity}</div><div class="activity-code">${x.code}</div></td><td>${x.project||'3.42 MWp-Tigadi-Deepak'}</td><td>${x.subprojectName||'Not set'}</td><td>${x.internalKey}</td><td>${x.rowNo}</td><td>${x.code}</td><td>${x.milestone}</td><td>${x.owner}</td><td>${formatNumber(x.qty)}</td><td>${formatNumber(x.unitPrice)}</td><td>${formatNumber(x.plannedBudget)}</td><td>${formatNumber(x.prQty)}</td><td>${formatNumber(x.prTotal)}</td><td>${formatNumber(x.prOpenQty)}</td><td>${formatNumber(x.poQty)}</td><td>${formatNumber(x.poTotal)}</td><td>${formatNumber(x.poOpenQty)}</td><td>${formatNumber(x.poBalanceValue)}</td><td>${formatNumber(x.grnQty)}</td><td>${formatNumber(x.grnOpenQty)}</td><td>${formatNumber(x.grnTotal)}</td><td>${formatNumber(x.invoiceQty)}</td><td>${formatNumber(x.invoiceTotal)}</td><td class="progress-cell"><div class="progress-value"><span>${x.progress}%</span></div><div class="bar-track"><div class="bar-fill ${x.status==='Overdue'?'amber':''}" style="width:${x.progress}%"></div></div></td><td><span class="status ${statusClass(x.status)}">${x.status}</span></td></tr>`).join('') || '<tr><td colspan="25" style="text-align:center;color:#75817d;padding:30px">No assignments match this view.</td></tr>'; }
function render(){renderMetrics();renderPeople();renderActivity();renderTable();}
function showToast(message){const toast=$('toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800);}
function downloadCsv(){const header='Activity,Code,Owner,Milestone,Due date,Progress,Status\n';const body=assignments.map(x=>[x.activity,x.code,x.owner,x.milestone,x.due,x.progress+'%',x.status].map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([header+body],{type:'text/csv'}));a.download='worktrack-assignments.csv';a.click();showToast('Assignment report exported.');}
function normalizeRows(rows){return rows.map((r,i)=>{const find=(names)=>{const key=Object.keys(r).find(k=>names.some(n=>k.toLowerCase().includes(n)));return key?r[key]:''};const activity=find(['bop activity','activity','work']);const code=find(['item code','code']);const owner=find(['assigned to','owner','employee','person'])||'Unassigned';const planned=Number(find(['qty','planned quantity']))||0;const done=Number(find(['invoice qty','grn qty','completed qty']))||0;const progress=planned?Math.min(100,Math.round(done/planned*100)):0;let status=progress>=100?'Completed':progress>0?'In progress':'Not started';return {activity:activity||`Imported activity ${i+1}`,code:code||'Imported',project:find(['project'])||'3.42 MWp-Tigadi-Deepak',subprojectName:find(['subproject name','subproject'])||'Not set',internalKey:reportValue(find(['internal key'])),rowNo:reportValue(find(['row no','row number'])),owner,initials:owner==='Unassigned'?'UN':owner.split(' ').map(x=>x[0]).join('').slice(0,2),milestone:find(['milestone'])||'Imported',due:find(['due date'])||'Not set',qty:reportValue(find(['qty'])),unitPrice:reportValue(find(['project unit price','unit price'])),plannedBudget:reportValue(find(['planned budget','budget'])),prQty:reportValue(find(['pr qty'])),prTotal:reportValue(find(['pr total'])),prOpenQty:reportValue(find(['pr open qty'])),poQty:reportValue(find(['po qty'])),poTotal:reportValue(find(['po total'])),poOpenQty:reportValue(find(['po open qty'])),poBalanceValue:reportValue(find(['po balance value'])),grnQty:reportValue(find(['grn qty','gnr qty'])),grnOpenQty:reportValue(find(['grn open qty'])),grnTotal:reportValue(find(['grn total'])),invoiceQty:reportValue(find(['invoice qty','invoice quality'])),invoiceTotal:reportValue(find(['invoice total'])),progress,status};});}
$('search-input').addEventListener('input',renderTable);$('status-filter').addEventListener('change',renderTable);$('export-button').addEventListener('click',downloadCsv);$('people-view').addEventListener('click',()=>{document.querySelector('.assignments-panel').scrollIntoView({behavior:'smooth'});});$('file-input').addEventListener('change',async(e)=>{const file=e.target.files[0];if(!file)return;try{const data=await file.arrayBuffer();const workbook=window.XLSX.read(data,{type:'array'});const sheet=workbook.Sheets[workbook.SheetNames[0]];assignments=normalizeRows(window.XLSX.utils.sheet_to_json(sheet,{defval:''}));$('last-import').textContent=file.name;setActiveReportName(file.name);render();if(window.recordViewedReport)window.recordViewedReport(file.name,assignments);showToast(`${assignments.length} assignments imported from ${file.name}`);}catch(error){showToast('Could not read this file. Please try again.');console.error(error);}});render();
async function loadBundledReport(){const savedReport=typeof viewedReports!=='undefined'?viewedReports.find((report)=>report.name==='Tigadi Deepak report 1111.xlsx')||viewedReports[0]:null;if(!savedReport)return;assignments=savedReport.rows; $('last-import').textContent=savedReport.name;setActiveReportName(savedReport.name); render();}
render();loadBundledReport();
